import LegalLayout from "./LegalLayout";
export default function CgvPage() {
  return (
    <LegalLayout
      title="Terms of Sale (CGV)"
      subtitle="General terms and conditions governing all sourcing, verification and matchmaking services provided by Afrisource Group."
      lastUpdated="May 1, 2026"
      sections={[
        { heading: "Company Identification", body: ["These General Terms of Sale (CGV) govern all commercial relationships between Afrisource Group (hereinafter 'the Company') and any client (hereinafter 'the Client') who engages our sourcing and export services.", ["Company name: Afrisource Group", "Founder & Director: Mohammed Hayoun", "Registered country: Morocco", "Contact: contact@afrisourcegroup.com", "Phone: +212 6 61 37 26 84"]] },
        { heading: "Scope of Services", body: ["Afrisource Group provides the following B2B services:", ["Supplier sourcing and identification across Morocco and Africa", "Supplier verification and audit (documentation, certifications, capacity)", "Buyer–supplier matchmaking and introduction", "Export consulting and documentation support", "Quality control coordination via third-party partners (SGS, Intertek, Cotecna, Bureau Veritas)"], "These terms apply to all services unless a separate written agreement is established between the parties."] },
        { heading: "Engagement & Orders", body: ["An engagement is formalised when the Client confirms acceptance of a service proposal or signs a service agreement. Verbal confirmations followed by written acknowledgement (email) are binding.", "Afrisource Group reserves the right to decline any engagement that conflicts with its ethical standards, compliance requirements, or capacity constraints."] },
        { heading: "Pricing & Payment Terms", body: ["Service fees are agreed upon in writing prior to engagement commencement. Fees may be structured as a fixed project fee, a success fee based on transaction value, or a combination thereof.", ["Invoices are payable within 30 days of issuance unless otherwise agreed", "Payments may be made by bank transfer to the account details provided on the invoice", "Late payments may incur a penalty of 1.5% per month on the outstanding balance", "All prices are exclusive of applicable taxes unless stated otherwise"]] },
        { heading: "Service Delivery", body: ["Afrisource Group will use commercially reasonable efforts to deliver services within agreed timescales. Delivery timelines are estimates and may be affected by third-party delays, supplier availability, or regulatory processes outside our control.", "The Company will keep the Client informed of material delays and propose solutions where possible."] },
        { heading: "Warranties & Guarantees", body: ["Afrisource Group warrants that it will perform services with professional care and skill. However, the Company does not guarantee the commercial outcome of any buyer–supplier introduction, the conclusion of any transaction, or the ultimate performance of any supplier.", "Supplier verifications are conducted to the best of our ability using available documentation and inspection. The Company cannot be held liable for supplier non-performance that occurs after the completion of our verification process."] },
        { heading: "Limitation of Liability", body: ["Afrisource Group's total liability for any claim arising from the provision of services is limited to the total fees paid by the Client for the specific service giving rise to the claim.", "The Company shall not be liable for any indirect, consequential, or incidental damages, including loss of profits, loss of business, or reputational damage."] },
        { heading: "Confidentiality", body: ["Both parties agree to keep confidential all proprietary, commercial, and technical information exchanged in the course of the engagement.", "This obligation of confidentiality survives the termination of the service agreement for a period of three (3) years."] },
        { heading: "Intellectual Property", body: ["All reports, analyses, supplier profiles, and other deliverables produced by Afrisource Group remain the intellectual property of the Company until full payment is received.", "Upon full payment, the Client receives a non-exclusive, non-transferable licence to use the deliverables for their internal business purposes."] },
        { heading: "Dispute Resolution", body: ["In the event of a dispute, the parties shall first attempt to resolve the matter amicably through direct negotiation. If no resolution is reached within 30 days, the dispute shall be referred to the competent courts of Morocco."] },
        { heading: "Applicable Law", body: ["These terms are governed by and construed in accordance with the laws of the Kingdom of Morocco."] },
      ]}
    />
  );
}